
import { Appearance } from 'react-native';

const colorScheme = Appearance.getColorScheme();

export const offlineImage = {
    google: require('../assets/images/google.png'),
    hotmail: require('../assets/images/hotmail.png'),
    activeOval: require('../assets/images/onboarding/active-oval.png'),
    email: require('../assets/images/email.png'),
    password: require('../assets/images/password.png'),
    inActiveOval: require('../assets/images/onboarding/inactive-oval.png'),
    splashScreen: require('../assets/images/onboarding/onboarding-bg.png'),
    onboarding0: require('../assets/images/onboarding/onboarding-1.jpg'),
    onboarding1: require('../assets/images/onboarding/onboarding-2.jpg'),
    onboarding2: require('../assets/images/onboarding/onboarding-3.jpg'),
    headerLogo: require('../assets/images/onboarding/shrine-logo-2.png'),
    goBackLight: require('../assets/images/go-back-white.png'),
    orDivide: require('../assets/images/or-divide.png'),
    eye: require('../assets/images/eye.png'),
    checkedIcon: require('../assets/images/check-icon.png'),
    profile: require('../assets/images/profile.png'),
    phone: require('../assets/images/phone.png'),
    user_avatar: require('../assets/images/user_avatar.png'),
    people: require('../assets/images/people.png'),
    red_camera: require('../assets/images/red_white_camera.png'),
    small_logo: require('../assets/images/small_logo.png'),
    send: require('../assets/images/send.png'),
    avatar_one: require('../assets/images/avatar_1.png'),
    avatar_two: require('../assets/images/avatar_2.png'),
    avatar_three: require('../assets/images/avatar_3.png'),
    avatar_four: require('../assets/images/avatar_4.png'),
    appLogo: require('../assets/images/onboarding/shrine-logo.png'),
    empty: require('../assets/images/empty.png'),
    profile_circle: require('../assets/images/profile_circle.png'),
    filter: require('../assets/images/filter.png'),
    user_red: require('../assets/images/user_red.png'),
    shirt: require('../assets/images/shirt.png'),
    laptop: require('../assets/images/laptop.png'),
    salad: require('../assets/images/salad.png'),
    emptyCardImg: require('../assets/images/empty_card.png'),
    plusIcon: require('../assets/images/plus-icon.png'),
    shoes: require('../assets/images/sneakers.png'),
    location_pin: require('../assets/images/location_pin.png'),
    paypal: require('../assets/images/paypal.png'),
    card: require('../assets/images/card_withdrawal.png'),
    online_user: require('../assets/images/online_user.png'),
    verify_badge: require('../assets/images/verified_badge.png'),
    location: require('../assets/images/location.png'),
    active_listing: require('../assets/images/active_listings.png'),
    change_password: require('../assets/images/change_password.png'),
    payment_method: require('../assets/images/payment_method.png'),
    communities: require('../assets/images/communities.png'),
    t_and_c: require('../assets/images/t_and_c.png'),
    orders_trolley: require('../assets/images/orders_trolley.png'),
    new_logout: require('../assets/images/logout.png'),
    red_color_user: require('../assets/images/red_color_user.png'),
    red_color_email: require('../assets/images/red_email.png'),
    red_color_phone: require('../assets/images/red_phone.png'),
    we_the_people: require('../assets/images/we_the_people.png'),
    rave: require('../assets/images/rave.png'),
    events_all: require('../assets/images/events_all.png'),
    events_air: require('../assets/images/events_air.png'),
    events_music: require('../assets/images/events_music.png'),
    purple_location: require('../assets/images/purple_location.png'),
    purple_calendar: require('../assets/images/purple_calendar.png'),
    white_plus: require('../assets/images/white_plus.png'),
    group_profile: require('../assets/images/profile_group.png'),
    right_arrow: require('../assets/images/right_arrow.png'),
    purple_ticket: require('../assets/images/purple_ticket.png'),
    light_purple_calendar: require('../assets/images/light_purple_calendar.png'),
    light_purple_location: require('../assets/images/light_purple_location.png'),
    //Dark
    goBackDark: require('../assets/images/go-back-l.png'),
} as any

export const onlineImage = {

}